### ISSUE TITLE
Add brief description of evil-mc

### ISSUE THREAD

**Issue by apj68** [Ben-PH/spacemacs-cheatsheet#1]
I looked all over for some description of _how to use_ `evil-mc` (including the [`evil-mc`](https://github.com/Ben-PH/spacemacs-cheatsheet) site).  Thanks to some help from `duianto` on [`spacemacs@gitter`](https://gitter.im/syl20bnr/spacemacs) I think I know enough to write up a short how-to.  This would be along the lines of your existing "quick guide for recurring use cases in magit".  I.e., just some landmarks to get someone going.

**Comment by Ben-PH** [comment]
That would be awesome.

You good to make a PR? I'm not too familiar enough with `evil-mc` to be comfortable putting one together, but if you'd like to, go for it.

**Comment by apj68** [comment]
Yup, will do!  Might take me some time to get a round tuit but would like to give it a shot.

**Comment by Ben-PH** [comment]
closed as per #2 

Thanks!
